### ISSUE TITLE
Some problems about DEMO.GUI & TrainingAnomalyDetector_public

### ISSUE THREAD

**Issue by VVVVictorJ** [WaqasSultani/AnomalyDetectionCVPR2018#22]
hi
I want to run the demo_Gui ,but i met some problems
First, PyQt4 can't work .So I replace it with PyQt5.
Then I met that.

('/home/victor/PycharmProjects/AnomalyDetectionCVPR2018/SampleVideos/Abuse/Abuse002_x264.mp4', 'All Files (*)')
Traceback (most recent call last):
  File "/home/victor/PycharmProjects/AnomalyDetectionCVPR2018/Demo_GUI.py", line 168, in SingleBrowse
    cap = cv2.VideoCapture(video_path)
TypeError: an integer is required (got type tuple)

I have no idea with that.
----------------------------------------------------------------------------------------------------------------------------------

Then I also met  some problem in the TrainingAnomalyDetector_public.

/home/victor/anaconda3/envs/AnomalyDetectionCVPR2018/bin/python /home/victor/PycharmProjects/AnomalyDetectionCVPR2018/TrainingAnomalyDetector_public.py
Using Theano backend.
/home/victor/.local/lib/python3.5/site-packages/theano/gpuarray/dnn.py:184: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to a version >= v5 and <= v7.
  warnings.warn("Your cuDNN version is more recent than "
Using cuDNN version 7301 on context None
Mapped name None to device cuda: GeForce GTX 960M (0000:01:00.0)
Create Model
Traceback (most recent call last):
  File "/home/victor/PycharmProjects/AnomalyDetectionCVPR2018/TrainingAnomalyDetector_public.py", line 279, in <module>
    model.compile(loss=custom_objective, optimizer=adagrad)
  File "/home/victor/.local/lib/python3.5/site-packages/keras/models.py", line 547, in compile
    **kwargs)
  File "/home/victor/.local/lib/python3.5/site-packages/keras/engine/training.py", line 622, in compile
    sample_weight, mask)
  File "/home/victor/.local/lib/python3.5/site-packages/keras/engine/training.py", line 324, in weighted
    score_array = fn(y_true, y_pred)
  File "/home/victor/PycharmProjects/AnomalyDetectionCVPR2018/TrainingAnomalyDetector_public.py", line 253, in custom_objective
    sub_sum_l1 = sub_sum_l1[:n_exp]
  File "/home/victor/.local/lib/python3.5/site-packages/theano/tensor/var.py", line 572, in __getitem__
    return theano.tensor.subtensor.advanced_subtensor(self, *args)
  File "/home/victor/.local/lib/python3.5/site-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/victor/.local/lib/python3.5/site-packages/theano/tensor/subtensor.py", line 2227, in make_node
    return super(AdvancedSubtensor, self).make_node(x, *index)
  File "/home/victor/.local/lib/python3.5/site-packages/theano/tensor/subtensor.py", line 2178, in make_node
    index = tuple(map(as_index_variable, index))
  File "/home/victor/.local/lib/python3.5/site-packages/theano/tensor/subtensor.py", line 2072, in as_index_variable
    return make_slice(idx)
  File "/home/victor/.local/lib/python3.5/site-packages/theano/gof/op.py", line 615, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/home/victor/.local/lib/python3.5/site-packages/theano/tensor/type_other.py", line 39, in make_node
    list(map(as_int_none_variable, inp)),
  File "/home/victor/.local/lib/python3.5/site-packages/theano/tensor/type_other.py", line 20, in as_int_none_variable
    raise TypeError('index must be integers')
TypeError: index must be integers

----------------------------------------------------------------------------------------------------------------------------------

I can't fix it.And I think the version can't match between the cudnn and Theano wasn't the reason casue 
it. 
I would really really appreciate it if you share a solution
thanks a lot !

**Comment by VivaaindreanNg** [comment]
Hey there.

Have you solved the issue on running with Demo_GUI? I'm having the same trouble as yours and couldn't exactly pinpoint why the error persists.

**Comment by VVVVictorJ** [comment]
> Hey there.
> 
> Have you solved the issue on running with Demo_GUI? I'm having the same trouble as yours and couldn't exactly pinpoint why the error persists.

Hi.
I didn't solve it.Could you tell me how to fix it if you deal with it?

**Comment by VivaaindreanNg** [comment]
> Hi.
> I didn't solve it.Could you tell me how to fix it if you deal with it?

Well, I've just managed to run the code. So, you just have to re-modify the type of output. The line: `cap = cv2.VideoCapture(video_path)` invokes an error because the output of **_QtGui.QFileDialog.getOpenFileName(...)_** returns you a tuple. 

So all you gotta do is to just add another placeholder, like this: 
`video_path, _ = QtGui.QFileDialog.getOpenFileName(...)` 
instead of just `video_path = QtGui.QFileDialog.getOpenFileName(...)` .

**Comment by VVVVictorJ** [comment]
> > Hi.
> > I didn't solve it.Could you tell me how to fix it if you deal with it?
> 
> Well, I've just managed to run the code. So, you just have to re-modify the type of output. The line: `cap = cv2.VideoCapture(video_path)` invokes an error because the output of **_QtGui.QFileDialog.getOpenFileName(...)_** returns you a tuple.
> 
> So all you gotta do is to just add another placeholder, like this:
> `video_path, _ = QtGui.QFileDialog.getOpenFileName(...)`
> instead of just `video_path = QtGui.QFileDialog.getOpenFileName(...)` .

Thank you very much. Do you run all the project successfull?
I also met some problem on the Testing_Anomaly_Detector_public.py 
It views that something with index.

**Comment by VivaaindreanNg** [comment]
Nah. So far the only module that I'm able to execute is the Demo_GUI. 

Are you able to run Training_Anomaly_Detector_public.py?

**Comment by VVVVictorJ** [comment]
> Nah. So far the only module that I'm able to execute is the Demo_GUI.
> 
> Are you able to run Training_Anomaly_Detector_public.py?

I didn't execute anyone. -_-
I also met some problem on Demo_Gui.
Would you met it ever?Could you tell me how to do if you fix it?
Like this:
/home/victor/PycharmProjects/AnomalyDetectionCVPR2018/SampleVideos/Explosion025_x264.txt
<module 'cv2' from '/home/victor/anaconda3/envs/AnomalyDetectionCVPR2018/lib/python3.5/site-packages/cv2.cpython-35m-x86_64-linux-gnu.so'>
Unable to stop the stream: Inappropriate ioctl for device
Traceback (most recent call last):
  File "/home/victor/PycharmProjects/AnomalyDetectionCVPR2018/Demo_GUI.py", line 184, in SingleBrowse
    F_Score = np.matlib.repmat(predictions[iv],1,(int(total_segments[iv+1])-int(total_segments[iv])))
AttributeError: module 'numpy' has no attribute 'matlib'
