### ISSUE TITLE
C3D model used in tests

### ISSUE THREAD

**Issue by roggerfq** [WaqasSultani/AnomalyDetectionCVPR2018#5]
According to what I have been able to review of the article and the source code, you did not perform training of the C3D neural network. I would like to know where I find the model files in the C3D directory tree. Thank you.

**Comment by kjsr7** [comment]
https://github.com/facebook/C3D

**Comment by Malathi15** [comment]
Hi @kjsr7 , I want to test my own video with pretrain model, but I don't know how to use C3D? they didn't gave any processor!

**Comment by kjsr7** [comment]
@Malathi15, you can use [this](@Shiny128, Use [this](https://docs.google.com/document/d/1-QqZ3JHd76JfimY4QKqOojcEaf5g3JS0lNh-FHTxLag) for extracting features for new videos.) guide to extract features.

**Comment by roggerfq** [comment]
> Hi @kjsr7 , I want to test my own video with pretrain model, but I don't know how to use C3D? they didn't gave any processor!

Hello, this algorithm is composed of two neural networks: a convolutional network and a fully-contected network. The convolutional network extracts the features and stores them in a binary format .fc6-1 (fc6 refers to the layer whose name is fc6 in the .prototext file, this layer has an output of 4096 components). Then use the "Save_C3DFeatures_32Segments.m" script to convert the .fc6-1 features to a text file. The name of this file will be name_video_C.txt. Finally, you must use the "Demo_GUI.py" script to read the text file and in this way you'll get a graph of anomalia versus time. If you have a doubt in the process you can write to roger.figueroa@javerianacali.edu.co

**Comment by Malathi15** [comment]
Hi @roggerfq  @kjsr7  I refered [this](roger.figueroa@javerianacali.edu.co) link. When I tried to extract the videos I got this error
```
python extract_C3D_feature.py input/avi/v_BaseballPitch_g01_c01.avi output
[Info] trained_model=C:\Users\malat\Desktop\C3D-master\C3D-v1.0\examples\c3d_feature_extraction\conv3d_deepnetA_sport1m_iter_1900000 found. Good to go!
[Info] num_frames=107, fps=29.97002997002997
Traceback (most recent call last):
  File "extract_C3D_feature.py", line 806, in <module>
    main()
  File "extract_C3D_feature.py", line 727, in main
    generate_feature_prototxt(feature_prototxt, input_file)
  File "extract_C3D_feature.py", line 636, in generate_feature_prototxt
    with open(out_file, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp\\feature_extraction.prototxt'
```

**Comment by abdkumar** [comment]
> @Malathi15, you can use [this](https://docs.google.com/document/d/1-QqZ3JHd76JfimY4QKqOojcEaf5g3JS0lNh-FHTxLag) guide to extract features.

But I didnt understand that file, how to download C3D model and how to test it. please help

**Comment by roggerfq** [comment]
> > @Malathi15, you can use [this](https://docs.google.com/document/d/1-QqZ3JHd76JfimY4QKqOojcEaf5g3JS0lNh-FHTxLag) guide to extract features.
> 
> But I didnt understand that file, how to download C3D model and how to test it. please help

C3D is based on caffe library and their directory structure, installation and the way of use are the same. I can give you a link where it is explained step by step installation process. By following these steps, I was able to install c3d correctly.

**First of all I recommend you Linux operating system.**

Download C3D repository from: 
https://github.com/facebook/C3D

Follow this installation process:
https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide
https://chunml.github.io/ChunML.github.io/project/Installing-Caffe-Ubuntu/

Next, Then run a test example following the guide: http://vlg.cs.dartmouth.edu/c3d/
