### ISSUE TITLE
python module error

### ISSUE THREAD

**Issue by ajmal-adfg** [WaqasSultani/AnomalyDetectionCVPR2018#7]
Hi,

I am using python 2.7, theano 1.0.2 and keras 1.1.0 and facing the below error while running the training module.

Connected to pydev debugger (build 182.4129.34)
Using TensorFlow backend.
Create Model
2018-08-30 15:19:32.201695: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/opt/pycharm-2018.2.2/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/opt/pycharm-2018.2.2/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-2018.2.2/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/msiddiqui/algorythma/AnomalyDetection_CVPR2018/TrainingAnomalyDetector_public.py", line 32, in <module>
    model.add(Dropout(0.6))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 514, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/core.py", line 90, in call
    x = K.in_train_phase(K.dropout(x, self.p, noise_shape), x)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 1304, in in_train_phase
    x = tf.python.control_flow_ops.cond(tf.cast(_LEARNING_PHASE, 'bool'),
AttributeError: 'module' object has no attribute 'python'
Exception TypeError: TypeError("'NoneType' object is not callable",) in <function _remove at 0x7f9bf157a7d0> ignored

**Comment by WaqasSultani** [comment]
The code is using "Using Teano backend.".
You are using "Using TensorFlow backend.".

**Comment by ajmal-adfg** [comment]
Thanks waqas. Its really helpful. The issue got resolved when i changed the backend from tensorflow to theano. there are two ways to do this. one from the profile ($HOME/.keras/keras.json) and other is the code you provided.
def set_keras_backend(backend):

if K.backend() != backend:
os.environ['KERAS_BACKEND'] = backend
importlib.reload(K)
assert K.backend() == backend

set_keras_backend("theano")
