### ISSUE TITLE
Is it necessary to use c3d to compile the training?

### ISSUE THREAD

**Issue by mh-y** [WaqasSultani/AnomalyDetectionCVPR2018#70]
Is it necessary to use c3d to compile the TrainingAnomalyDetector_public.py?

When I put Explosion008_x264.txt RoadAccidents002_x264.txt Shooting033_x264.txt Explosion025_x264.txt RoadAccidents022_x264.txt Shoplifting028_x264.txt, etc. in AllClassPath(Path), and put wiights_L1L2.mat, model.json in the Output_dir(Path) and then i got the error:

Using Theano backend.
Create Model
Starting training...
All_class_files :  ['Explosion008_x264.txt', 'Explosion025_x264.txt', 'Normal_Videos_006_x264.txt', 'Normal_Videos_024_x264.txt', 'RoadAccidents002_x264.txt', 'RoadAccidents022_x264.txt', 'RoadAccidents123_x264.txt', 'Shooting008_x264.txt', 'Shooting033_x264.txt', 'Shoplifting028_x264.txt']
// my printing
All_class_files[0] :  Explosion008_x264.txt  //my printing
All_class_files[1] :  Explosion025_x264.txt  // my printing
AbnormalPath :  ./C3D/Explosion008_x264.txt  // my printing
AllVideos_Path :  ./C3D/Explosion008_x264.txt  // my printing
AllVideos :  []  // my printing
Loading Abnormal videos Features...
before error for syntex
AllVideos_Path :  ./C3D/Explosion008_x264.txt  // my printing
ALL_Videos :  []  // my printing
Traceback (most recent call last):
  File "TrainingAnomalyDetector_public.py", line 330, in <module>
    inputs, targets=load_dataset_Train_batch(AbnormalPath, NormalPath)  # Load normal and abnormal video C3D features
  File "TrainingAnomalyDetector_public.py", line 141, in load_dataset_Train_batch
    VideoPath = os.path.join(AllVideos_Path, All_Videos[iv])
IndexError: list index out of range

What is the preparation sequence for running this program?

**Comment by mh-y** [comment]
i solved this problem
