### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'units' when run Test_Anomaly_Detector_public.py

### ISSUE THREAD

**Issue by vovantuan1999a** [WaqasSultani/AnomalyDetectionCVPR2018#74]
Traceback (most recent call last):
  File "Test_Anomaly_Detector_public.py", line 112, in <module>
    model=load_model(model_path)
  File "Test_Anomaly_Detector_public.py", line 35, in load_model
    model = model_from_json(open(json_path).read())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/models.py", line 360, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 163, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/models.py", line 1237, in from_config
    layer = layer_module.deserialize(conf, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 165, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 475, in from_config
    return cls(**config)
TypeError: __init__() missing 1 required positional argument: 'units'
Hi.
I'm study in university.
I follow paper for academic purposes. While I ran Test_Anomaly_Detector_public.py, I got this error. I hope the author can help me fix this error. 
Best regards

**Comment by hello-ht** [comment]
Hello, I want to ask you whether this problem is solved, I also encountered the same problem

**Comment by hazemfahmyy** [comment]
I solved the problem by changing the name "output_dims" to "units" in the json file

**Comment by hello-ht** [comment]
Thank you very much, you are right. The model must have the unit parameter, I added the unit to Json

**Comment by vovantuan1999a** [comment]
Thank you for your respone.

This is helpful for me.

Thank you and best regards.

Vào 20:38, Th 6, 23 thg 4, 2021 hello-ht ***@***.***> đã viết:

**Comment by FatimaDua** [comment]
> I solved the problem by changing the name "output_dims" to "units" in the json file

It helped me, Thank you aalot
